/* Additional record code for multary_simplification generated by the OpenModelica Compiler OMCompiler v1.19.0-dev.431+g3379db1584. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "multary_simplification_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

